/** Preserve notices for third-party code included in the inspector bundle. */
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const frontend = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repository = resolve(frontend, "..");
const require = createRequire(resolve(frontend, "package.json"));
const reactDOMRequire = createRequire(
  require.resolve("react-dom/package.json"),
);

const dependencies = [
  ["react", require],
  ["react-dom", require],
  ["scheduler", reactDOMRequire],
  ["lucide-react", require],
];

const notices = await Promise.all(
  dependencies.map(async ([name, resolver]) => {
    // Resolve the installed package rather than guessing pnpm's store layout.
    // Scheduler must follow react-dom's own dependency, not a hoisted version.
    const manifestPath = resolver.resolve(`${name}/package.json`);
    const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
    const license = await readFile(
      resolve(dirname(manifestPath), "LICENSE"),
      "utf8",
    );
    if (manifest.name !== name || !manifest.version || !license.trim()) {
      throw new Error(`Missing package metadata or license text for ${name}`);
    }
    return {
      name,
      version: manifest.version,
      licenseId: manifest.license,
      license,
    };
  }),
);

const introduction =
  "The Rebound inspector includes the third-party packages listed below. " +
  "Their upstream copyright and permission notices are reproduced in full.\n\n" +
  "Generated by frontend/scripts/build-notices.mjs from the installed package " +
  "versions after the frontend build. These notices cover the bundled frontend " +
  "runtime dependencies; separately installed development and Python dependencies " +
  "retain their own license files.\n";

const markdown =
  "# Third-party notices\n\n" +
  introduction +
  notices
    .map(
      ({ name, version, licenseId, license }) =>
        `\n## ${name} ${version}\n\nDeclared license: ${licenseId}\n\n` +
        "```text\n" +
        license +
        (license.endsWith("\n") ? "" : "\n") +
        "```\n",
    )
    .join("");

const plainText =
  "THIRD-PARTY NOTICES\n\n" +
  introduction +
  notices
    .map(
      ({ name, version, licenseId, license }) =>
        `\n${"=".repeat(72)}\n${name} ${version}\nDeclared license: ${licenseId}\n\n` +
        license +
        (license.endsWith("\n") ? "" : "\n"),
    )
    .join("");

const staticDirectory = resolve(repository, "src/rebound/static");
await mkdir(staticDirectory, { recursive: true });
await Promise.all([
  writeFile(resolve(repository, "THIRD_PARTY_NOTICES.md"), markdown),
  writeFile(resolve(staticDirectory, "THIRD_PARTY_NOTICES.txt"), plainText),
]);
process.stdout.write(
  `Preserved upstream notices: ${notices.map(({ name, version }) => `${name}@${version}`).join(", ")}\n`,
);
